In [3]:
new=[]
num=[1,2,3,4]
for i in num:
    new.append(i**2)
print(new)

[1, 4, 9, 16]


In [4]:
new = [i**2 for i in num]
print(new)

[1, 4, 9, 16]


In [ ]:
num=[1,2,3,4,5,6,8,9]
#Generate a list with square of numbers
#but consider only even numbers form the given list

In [6]:
evenlist = []

for i in num:
    if(i%2==0):
        evenlist.append(i**2)
print(evenlist)

[4, 16]


In [7]:
#list comprehension
#new=[output iterable condition]
new=[i**2 for i in num if(i%2==0)]
new

[4, 16]

In [9]:
prices=[100,200,250,300,450]
newprices=[]
for i in prices:
    newprices.append(i+(i/100*7))
print(newprices)

[i*1.07 for i in prices]


[107.0, 214.0, 267.5, 321.0, 481.5]


[107.0, 214.0, 267.5, 321.0, 481.5]

In [18]:
text="Asset in worth 24000000 and liability is 1200000"
newlist=text.split()
new=[]
for w in newlist:
    new.append(int(w))
new

ValueError: invalid literal for int() with base 10: 'Asset'

In [14]:
new=[int(w) for w in text.split() if w.isdigit()]

In [15]:
new

[24000000, 1200000]

In [20]:
#generate a list of ROI:10% for term deposits,
#15%for govt bonds, 20%for T bills
investment = ["GBonds","Tbills","Term","Term","TBills"]
roi=[]
for i in investment:
    if i == "GBonds":
        roi.append(0.15)
    elif i=="Tbills":
        roi.append(0.20)
    else:
        roi.append(0.10)
print(roi)

[0.15, 0.2, 0.1, 0.1, 0.1]


In [27]:
roi=[0.15 if i =="GBonds" else 0.2 if i=="Tbills"\
    else 0.10 for i in investment]
     
roi

[0.15, 0.2, 0.1, 0.1, 0.1]

In [28]:
#user difine function
def srm_add(price,tax):
    total=price+tax
    print(total)
    

In [29]:
srm_add(200,14)


214


In [30]:
srm_add(500,90)

590


In [34]:
#CAN YOU WRITE FUNCTION
#that can accept a string
#and return you a list of dits if 
#digits are present in the string


def write_dig(text):
    new=[int(w) for w in text.split() if w.isdigit()]
    return(new)

write_dig("This is a 1000 2200 queue for rich people who have 1000000 salary")    

[1000, 2200, 1000000]

In [35]:
def srm_rate(total,qty):
    unit=total/qty
    return(unit)

In [36]:
z=srm_rate(300,10)
z

30.0

In [38]:
z=srm_rate(qty=10,total=300)
z

30.0

In [39]:
z=srm_rate(300,20)

In [40]:
z

15.0

#Required Arguments
#keyword arguments
#Default Arguments
#Variable-lenght Argument
#Variable-Lenght keyword Arguments

In [41]:
#*froms a tuple
def srm_add_all(*num):
    print(num)
srm_add_all(1,2,3,4,5,6)
    

(1, 2, 3, 4, 5, 6)


In [45]:
def srm_add_n(*num):
    addval=0
    for i in num:
        addval = addval+i
    return(addval)
srm_add_n(1,2,3,4,5,6)

21

In [47]:
def srm_data(**info):
    print(info)

In [48]:
srm_data(name="John",age=20,qlf="Masters")

{'name': 'John', 'age': 20, 'qlf': 'Masters'}


In [51]:
srm_data(name="john",prod="soap",store=["A","B","C"])

{'name': 'john', 'prod': 'soap', 'store': ['A', 'B', 'C']}


In [52]:
def srm_value(rate,tax,qty):
    cost_before_tax=rate*qty
    cost_after_tax=cost_before_tax+tax
    return cost_before_tax,cost_after_tax

In [53]:
abc,bac = srm_value(10,500,100)
print(abc)
print(bac)

1000
1500


In [54]:
lambda x:x+1

<function __main__.<lambda>(x)>

In [55]:
result = lambda x:x+1
result(6)

7

In [56]:
result=lambda x:x**2+1+x**3+5
result(10)

1106

In [59]:
fn="jhon"
ln="taylor"
fullname=lambda fn, ln :fn.title()+" "+ln.title()
fullname(fn,ln)

'Jhon Taylor'

In [60]:
names=["Ramesh Nair","John Taylor","Swathi Reddy","Manash Kumar"]
#sort the list
names.sort()
names

['John Taylor', 'Manash Kumar', 'Ramesh Nair', 'Swathi Reddy']

In [61]:
#sort the list by last naem
names=["Ramesh Nair","John Taylor","Swathi Reddy","Manash Kumar"]
names.sort(key=lambda x:x.split(" ")[1])
names

['Manash Kumar', 'Ramesh Nair', 'Swathi Reddy', 'John Taylor']

In [64]:
items=[("apples",87),("orange",54),("grapres",59),("kiwi",117)]
#sort by amount
items.sort(key=lambda x:x[1])
items


[('orange', 54), ('grapres', 59), ('apples', 87), ('kiwi', 117)]

In [66]:
emp =[{"name":"John","age":23,"YOJ":2016},\
     {"name":"Mary","age":32,"YOJ":2019},\
     {"name":"TOmmy","age":199,"YOJ":2017},\
     {"name":"Henry","age":40,"YOJ":2020}]

In [68]:
emp.sort(key=lambda x:x['YOJ'],reverse=True)
emp

[{'name': 'Henry', 'age': 40, 'YOJ': 2020},
 {'name': 'Mary', 'age': 32, 'YOJ': 2019},
 {'name': 'TOmmy', 'age': 199, 'YOJ': 2017},
 {'name': 'John', 'age': 23, 'YOJ': 2016}]

In [2]:
import numpy as np
weigth=[57,63,73,64]
weigth_array=np.array(weigth)
print("Weight_array",weigth_array)

Weight_array [57 63 73 64]


In [5]:
print('type of weight',type(weigth))

type of weight <class 'list'>


In [6]:
np.random.random(size=100)
#random = [will include 0 but not include 1)

array([0.31978541, 0.03776795, 0.22352318, 0.44661829, 0.35971312,
       0.70613379, 0.6988188 , 0.27382991, 0.66675441, 0.48110863,
       0.81400965, 0.96884255, 0.51729604, 0.30489974, 0.59944779,
       0.43569424, 0.75681026, 0.75905382, 0.44862918, 0.09833394,
       0.38674327, 0.36253171, 0.29979691, 0.36387157, 0.42798214,
       0.13873633, 0.37874764, 0.5664301 , 0.60994455, 0.83601679,
       0.41558502, 0.54011598, 0.50407273, 0.65670181, 0.33538282,
       0.48487475, 0.95185299, 0.11639751, 0.86444286, 0.1895583 ,
       0.24285137, 0.66518729, 0.90716467, 0.96819381, 0.78925946,
       0.30997302, 0.55853523, 0.84064779, 0.88163331, 0.35944546,
       0.76625838, 0.25431085, 0.55600929, 0.47741838, 0.3911635 ,
       0.28095693, 0.93418301, 0.18009547, 0.88240092, 0.07561401,
       0.03272799, 0.3303323 , 0.99447748, 0.40643567, 0.93880159,
       0.50762619, 0.10689835, 0.46040954, 0.3371684 , 0.60188468,
       0.23323708, 0.23746092, 0.90986953, 0.52442378, 0.00144

In [7]:
np.random.rand(5)
#uniform distribution (between 0 to 1)

array([0.66371716, 0.89759732, 0.69541904, 0.52099382, 0.24259614])

In [8]:
np.random.randn(5)
#standard distribution

array([-0.14313726,  0.08393085, -0.11897772,  0.3025749 , -0.05943983])

In [9]:
np.random.randint(5,20)

17

In [10]:
np.random.randint(5,20,6)

array([12,  7,  7,  5,  5, 12])

In [15]:
even_num=np.arange(start=33,stop=3301,step=33)
even_num
#end number is not included

array([  33,   66,   99,  132,  165,  198,  231,  264,  297,  330,  363,
        396,  429,  462,  495,  528,  561,  594,  627,  660,  693,  726,
        759,  792,  825,  858,  891,  924,  957,  990, 1023, 1056, 1089,
       1122, 1155, 1188, 1221, 1254, 1287, 1320, 1353, 1386, 1419, 1452,
       1485, 1518, 1551, 1584, 1617, 1650, 1683, 1716, 1749, 1782, 1815,
       1848, 1881, 1914, 1947, 1980, 2013, 2046, 2079, 2112, 2145, 2178,
       2211, 2244, 2277, 2310, 2343, 2376, 2409, 2442, 2475, 2508, 2541,
       2574, 2607, 2640, 2673, 2706, 2739, 2772, 2805, 2838, 2871, 2904,
       2937, 2970, 3003, 3036, 3069, 3102, 3135, 3168, 3201, 3234, 3267,
       3300])

In [17]:
even_num=np.linspace(start=33,stop=3300,num=33)
even_num
#end number is included
#it gives float


array([  33.     ,  135.09375,  237.1875 ,  339.28125,  441.375  ,
        543.46875,  645.5625 ,  747.65625,  849.75   ,  951.84375,
       1053.9375 , 1156.03125, 1258.125  , 1360.21875, 1462.3125 ,
       1564.40625, 1666.5    , 1768.59375, 1870.6875 , 1972.78125,
       2074.875  , 2176.96875, 2279.0625 , 2381.15625, 2483.25   ,
       2585.34375, 2687.4375 , 2789.53125, 2891.625  , 2993.71875,
       3095.8125 , 3197.90625, 3300.     ])

In [18]:
#create Nympy array

np.zeros(shape=4)
a=np.zeros(shape=4)
a.shape

(4,)

In [19]:
np.ones(shape=5)

array([1., 1., 1., 1., 1.])

In [26]:
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
matrix_empty= np.empty((2,2),dtype=float)
matrix_empty

array([[6.95277474e-310, 6.95277474e-310],
       [6.95277474e-310, 6.95277474e-310]])

In [29]:
#create a full matrix np.full
matrix_full= np.full((2,2),fill_value=10)
matrix_full

array([[10, 10],
       [10, 10]])

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Attributes will not have any brakets at the end 
#few attributed are 
#size
#Shape
#ndim
#dtype


In [34]:
original_array=np.array([(4,9),(7,2),(5,6)])
print("Original array",original_array)

reshape_array=original_array.reshape(2,3)
print("reshape array",reshape_array)


Original array [[4 9]
 [7 2]
 [5 6]]
reshape array [[4 9 7]
 [2 5 6]]


In [38]:
weight=np.array([(20,30,40),(50,60,70)])
print("second row",weight[1,:])
print("second row",weight[1])
print("second row",weight[0,:2])
print("second row",weight[0:1,0:1])

second row [50 60 70]
second row [50 60 70]
second row [20 30]
second row [[20]]


In [ ]:
#array[rows,column]


In [41]:
#array comparison

age=np.array([13,45,22,6,14,25])
print('age greater than 18:',age>18)
print('age greater than 18:',age[age>18])
#array[Filtering.Condition]

age greater than 18: [False  True  True False False  True]
age greater than 18: [45 22 25]


In [42]:
num_array=np.array([1,2,3,4,5])
print('update_array:',num_array*2)

update_array: [ 2  4  6  8 10]


In [49]:
num_matrix_1=np.array([[1,0,2],[4,2,3]])
num_matrix_2=np.array([[4,0,1],[2,3,0]])

num_matrix_1



array([[1, 0, 2],
       [4, 2, 3]])

In [50]:
num_matrix_2

array([[4, 0, 1],
       [2, 3, 0]])

In [51]:
prod = num_matrix_1*num_matrix_2
prod

array([[4, 0, 2],
       [8, 6, 0]])

In [52]:
age=np.array([14,74,84,26,56])
print("Minimum",age.min())

Minimum 14


In [53]:
print("Minimum",age.sum())

Minimum 254


In [54]:
print("Minimum",age.mean())

Minimum 50.8


In [55]:
print("Variance:",age.var())

Variance: 727.36


In [56]:
print("Standard Variance:",age.std())

Standard Variance: 26.969612529660118


In [57]:
print("Square:",np.square(age))

Square: [ 196 5476 7056  676 3136]


In [58]:
print("Square:",np.power(age,3))

Square: [  2744 405224 592704  17576 175616]


In [59]:
print('Transpose:',np.transpose(prod))

Transpose: [[4 8]
 [0 6]
 [2 0]]


In [60]:
order_1=np.array([1,4,5,7])
order_2=np.array([6,9,3])
order_3=np.array([2,7,5,9])

np.concatenate([order_1,order_2,order_3])

array([1, 4, 5, 7, 6, 9, 3, 2, 7, 5, 9])

In [61]:
odd_array = np.array([[1,3],[5,7]])
even_array=np.array([[2,4],[6,8]])

print("Concatenate row wise:", np.concatenate([odd_array,even_array]))
print("Concatenate column wise:", np.concatenate([odd_array,even_array],axis=1))

Concatenate row wise: [[1 3]
 [5 7]
 [2 4]
 [6 8]]
Concatenate column wise: [[1 3 2 4]
 [5 7 6 8]]
